name: Scaffold create-react-app
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  cra:
    runs-on: ubuntu-latest
    steps:
      # We need to check out first so that we have a baseline to make a diff of
      - name: Check out the existing scaffolded source code to make the change against
        uses: actions/checkout@v3

      # Set up Git baseline branch and identity before making any changes
      - name: Commit and push the change to the GitHub repository from the agent
        run: |
          # Configure Git for the push from the workflow to the repository
          # (This is needed even with the workflow PAT)
          git config --global user.email "tomas@hubelbauer.net"
          git config --global user.name "Tomas Hubelbauer"

          # Check out the `master` branch - GitHub Actions checks out detached HEAD
          git checkout master

      # Reset the directory repository to an empty state for new CRA run
      - name: Delete everything but the `.github` repository directory
        run: |
          # Enable dotglob to make sure the glob pattern matches hidden dotfiles as well
          shopt -s dotglob

          # Walk the repository directory entries and delete everything but `.github` and `.git`
          for name in ./*
          do
            if [ $name == "./.github" ] || [ $name == "./.git" ]
            then
              continue
            fi

            echo $name
            rm -rf $name
          done

      # This will also attempt to initialize a Git repository and fail (no Git
      # identity set up on the build agent) and it will install the Node NPM
      # dependencies, neither of which we can prevent due to lacking CLI options
      # Git: https://github.com/facebook/create-react-app/issues/9502
      # NPM: https://github.com/facebook/create-react-app/issues/9792
      - name: Install and scaffold create-react-app
        run: npx create-react-app cra

      # Remove the forcibly installed Node moduels through NPM
      # See https://github.com/facebook/create-react-app/issues/9792
      - name: Remove installed node_modules directory (unused in the workflow)
        run: rm -rf cra/node_modules

      # `cra/` works on macOS but doesn't work on Ubuntu without the extra `.`
      # I could use `mv` here but it is annoying and `cp` works and we delete
      # the `cra` directory afterwards anyway
      - name: Copy the contents of `cra` out to the repository directory
        run: cp -r cra/. .

      # The directory has become empty as we moved out all of its contents up
      - name: Delete the now empty `cra` directory
        run: rm -rf cra

      # This PAT is provided by the GitHub Actions runtime and is good for
      # everything but it will not cause GitHub Pages to deploy when pushed with
      - name: Authenticate with GitHub using the out of the box PAT
        run: git remote set-url origin https://tomashubelbauer:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}

      - name: Stage the changes resulting from the above steps
        run: git add *

      - name: Bail if there are no changes staged to commit
        id: bail
        run: |
          if git diff-index --quiet HEAD --; then
            exit
          fi

      - name: Echo the bail step output for debugging
        run: echo "${{steps.run_tests.outputs.*}}"

      - name: Commit the staged changes to the workflow repository
        run: git commit -m "Update CRA template generated source code"

      - name: Rebase if the branch has changed meanwhile or fail on conflicts
        run: git pull --rebase

      - name: Push the commit to the workflow repository
        run: git push
